compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
downcast_bf16: 'no'
fsdp_config: {}
machine_rank: 0
main_process_ip: gpu4.lan
main_process_port: 29500
main_training_function: main
mixed_precision: fp16
num_machines: 6
num_processes: 12
use_cpu: false
